/* Builds the Korean pages (ko/*.html) from the English pages + KO / KO_META in site.js.
 *
 *   node tools/build-ko.mjs
 *
 * Run it after changing any English page or any Korean text in site.js, then commit ko/ too.
 * The generated pages carry Korean body text in the HTML itself, so search engines index
 * them as Korean pages (https://www.leeeunsangtax.com/ko/...).
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = 'https://www.leeeunsangtax.com';
const PAGES = { 'index.html': '/', 'about.html': '/about', 'practice.html': '/practice', 'contact.html': '/contact' };

// Load KO / KO_META from site.js without a browser
const ctx = { tailwind: {}, document: { addEventListener() {} }, window: {}, navigator: {} };
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'site.js'), 'utf8') + '\n;globalThis.__out = { KO, KO_META };', ctx);
const { KO, KO_META } = ctx.__out;

const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escAttr = (s) => esc(s).replace(/"/g, '&quot;');
const koUrl = (p) => SITE + (p === '/' ? '/ko/' : '/ko' + p);

let problems = 0;
const fail = (msg) => { console.error('ERROR: ' + msg); problems++; };

fs.mkdirSync(path.join(ROOT, 'ko'), { recursive: true });

for (const [file, urlPath] of Object.entries(PAGES)) {
  let html = fs.readFileSync(path.join(ROOT, file), 'utf8');
  const page = (html.match(/<body[^>]*\sdata-page="(\w+)"/) || [])[1];
  const meta = KO_META[page];
  if (!meta) { fail(`${file}: no KO_META.${page}`); continue; }

  // 1) Body text: every [data-i18n] element holds plain text only
  const total = (html.match(/\sdata-i18n="/g) || []).length;
  let done = 0;
  html = html.replace(/(<([a-z0-9]+)\b[^>]*?\sdata-i18n="([^"]+)"[^>]*>)([^<]*)(<\/\2>)/g, (m, open, tag, key, text, close) => {
    done++;
    if (KO[key] === undefined) { fail(`${file}: KO.${key} missing`); return m; }
    return open + esc(KO[key]) + close;
  });
  if (done !== total) fail(`${file}: ${total - done} [data-i18n] element(s) contain markup and were not translated`);

  // 2) Placeholders
  html = html.replace(/(<[^>]*?\sdata-i18n-ph="([^"]+)"[^>]*>)/g, (tagHtml, _t, key) => {
    if (KO[key] === undefined) { fail(`${file}: KO.${key} missing`); return tagHtml; }
    return tagHtml.replace(/placeholder="[^"]*"/, `placeholder="${escAttr(KO[key])}"`);
  });

  // 3) <head>: language, title, description, canonical (hreflang block is shared with the English page)
  const head = [
    [/<html lang="en"/, '<html lang="ko"'],
    [/<title>[\s\S]*?<\/title>/, `<title>${esc(meta.title)}</title>`],
    [/<meta name="description" content="[^"]*" \/>/, `<meta name="description" content="${escAttr(meta.description)}" />`],
    [/<link rel="canonical" href="[^"]*" \/>/, `<link rel="canonical" href="${koUrl(urlPath)}" />`],
  ];
  for (const [re, to] of head) {
    if (!re.test(html)) fail(`${file}: ${re} not found`);
    html = html.replace(re, () => to);
  }
  if (!html.includes(`hreflang="ko" href="${koUrl(urlPath)}"`)) fail(`${file}: hreflang links missing in the English page`);

  // 4) JSON-LD: Korean description and URL
  html = html.replace(/(<script type="application\/ld\+json">)([\s\S]*?)(<\/script>)/g, (m, open, json, close) => {
    const data = JSON.parse(json);
    data.url = koUrl(urlPath);
    data.description = meta.description;
    return `${open}\n${JSON.stringify(data, null, 2).replace(/^/gm, '  ')}\n  ${close}`;
  });

  // 5) Shared files live at the site root (pages links stay relative, so they stay inside /ko/)
  html = html
    .replace(/(href|src)="(site\.css|site\.js)"/g, '$1="/$2"')
    .replace(/src="images\//g, 'src="/images/');

  html = html.replace(/^<!DOCTYPE html>\r?\n/i, (d) =>
    d + `<!-- Generated by tools/build-ko.mjs from ../${file} + site.js (KO, KO_META). Do not edit by hand. -->\n`);

  fs.writeFileSync(path.join(ROOT, 'ko', file), html);
  console.log(`ko/${file}  ${done} texts  ${meta.title}`);
}

if (problems) { console.error(`\n${problems} problem(s).`); process.exit(1); }
